const initModel = {
        "Age": "49",
        "Attrition": "No",
        "BusinessTravel": "Travel_Frequently",
        "DailyRate": "279",
        "Department": "Research & Development",
        "DistanceFromHome": "8",
        "Education": "1",
        "EducationField": "Life Sciences",
        "EnvironmentSatisfaction": "3",
        "Gender": "Male",
        "HourlyRate": "61",
        "JobInvolvement": "2",
        "JobLevel": "2",
        "JobRole": "Research Scientist",
        "JobSatisfaction": "2",
        "MaritalStatus": "Married",
        "MonthlyIncome": "5130",
        "MonthlyRate": "24907",
        "NumCompaniesWorked": "1",
        "Over18": "Y",
        "OverTime": "No",
        "PercentSalaryHike": "23",
        "PerformanceRating": "4",
        "RelationshipSatisfaction": "4",
        "StockOptionLevel": "1",
        "TotalWorkingYears": "10",
        "TrainingTimesLastYear": "3",
        "WorkLifeBalance": "3",
        "YearsAtCompany": "10",
        "YearsInCurrentRole": "7",
        "YearsSinceLastPromotion": "1",
        "YearsWithCurrManager": "7"
      }
export default initModel;